### ISSUE TITLE
Помилка в перекладі підстатті "Обробка подій"

### ISSUE THREAD

**Issue by Yudzhyn** [vuejs-translations/docs-uk#288]
[Посиллання на статтю](https://ua.vuejs.org/guide/essentials/event-handling.html#exact-modifier)

```
<!-- це спрацює лише тоді, коли не натиснуто Ctrl і жодних інших клавіш -->
<button @click.ctrl.exact="onCtrlClick">A</button>
```

Думаю що тут мало б бути:
`<!-- це спрацює лише тоді, коли натиснуто Ctrl і жодних інших клавіш -->`

Англійський переклад:
`<!-- this will only fire when Ctrl and no other keys are pressed -->`

**Comment by matrunchyk** [comment]
@Yudzhyn дякую за підказку!
