### ISSUE TITLE
Detach this repo as a fork from vuejs/docs

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-uk#295]
Hi docs-uk maintainers, as part of the translation guidelines:

> Before performing the transfer, use the GitHub support request to [detach your fork](https://support.github.com/request/fork). This is necessary because GitHub doesn't allow multiple forks of the same source repo to co-exist in the same organization.

would you mind detaching this fork via this link https://support.github.com/request/fork?

Thanks.

**Comment by matrunchyk** [comment]
@Jinjiang Submitted a ticket, will be detached soon! 

Sorry for late reply, just noticed the Issue
