### ISSUE TITLE
SSR title typo

### ISSUE THREAD

**Issue by yurhasko** [vuejs-translations/docs-uk#310]
Typo in https://ua.vuejs.org/guide/scaling-up/ssr.html#server-side-rendering-ssr title

https://github.com/vuejs-translations/docs-uk/blob/e50841913ef10cc6a68273768add7dea1260ae2f/src/guide/scaling-up/ssr.md?plain=1#L5C3-L5C14 -> "Рендеринг на стороні серверу"

**Comment by matrunchyk** [comment]
Дякую! Буду вдячний, якщо можете відкрити PR з даною зміною :)

**Comment by yurhasko** [comment]
> Дякую! Буду вдячний, якщо можете відкрити PR з даною зміною :)

https://github.com/vuejs-translations/docs-uk/pull/311/files
